 ---
  - name: updating system
    apt:
      upgrade: yes
      update_cache: yes

  - name: adding user
    become: true
    become_user: postgres
    postgresql_user:
      name: ubuntu
      role_attr_flags: CREATEDB,SUPERUSER
      state: present
  - name: adding database
    become: true
    become_user: postgres
    postgresql_db:
      name: ubuntu
      owner: ubuntu
      state: present
  - name: rename config file
    copy:
      remote_src: True
      src: /etc/postgresql/12/main/pg_hba.conf
      dest: /home/ubuntu/pg_hba.conf
  - name: Remove old file
    file:
      path: /etc/postgresql/12/main/pg_hba.conf
      state: absent

  - name: change permissions 1
    postgresql_pg_hba:
      dest: /etc/postgresql/12/main/pg_hba.conf
      contype: local
      users: postgres
      databases: all
      method: trust
      create: true

  - name: change permissions 2
    postgresql_pg_hba:
      dest: /etc/postgresql/12/main/pg_hba.conf
      contype: local
      users: all
      databases: all
      method: trust

  - name: change permissions 3
    postgresql_pg_hba:
      dest: /etc/postgresql/12/main/pg_hba.conf
      contype: host
      users: all
      source: 127.0.0.1/32
      databases: all
      method: trust

  - name: change permissions 4
    postgresql_pg_hba:
      dest: /etc/postgresql/12/main/pg_hba.conf
      contype: host
      users: all
      source: ::1/128
      databases: all
      method: trust

  - name: change permissions 5
    postgresql_pg_hba:
      dest: /etc/postgresql/12/main/pg_hba.conf
      contype: local
      users: all
      databases: replication
      method: peer

  - name: change permissions 6
    postgresql_pg_hba:
      dest: /etc/postgresql/12/main/pg_hba.conf
      contype: host
      users: all
      source: 127.0.0.1/32
      databases: replication
      method: md5

  - name: change permissions 7
    postgresql_pg_hba:
      dest: /etc/postgresql/12/main/pg_hba.conf
      contype: host
      users: all
      source: ::1/128
      databases: replication
      method: md5

