---
  - name: updating system
    apt:
      upgrade: yes
      update_cache: yes
      
  - name: Execute the command in remote shell; stdout goes to the specified file on the remote
    shell: sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
    
  - name: add key for postgresql
    apt_key: 
      url: https://www.postgresql.org/media/keys/ACCC4CF8.asc 
      state: present 
      
  - name: updating system
    apt:
      upgrade: yes
      update_cache: yes
      
  - name: installing postgresql
    package: name=postgresql-12 state=latest

  - name: adding user
    become: true
    become_user: postgres
    postgresql_user:
      name: ubuntu
      role_attr_flags: CREATEDB,SUPERUSER
      state: present
  - name: adding database
    become: true
    become_user: postgres
    postgresql_db:
      name: ubuntu
      owner: ubuntu
      state: present

  - name: change permissions 1
    postgresql_pg_hba:
      dest: /etc/postgresql/12/main/pg_hba.conf
      contype: local
      users: postgres
      databases: all
      method: trust
      create: true
    notify:
    - restarting postgresql

  - name: change permissions 2
    postgresql_pg_hba:
      dest: /etc/postgresql/12/main/pg_hba.conf
      contype: local
      users: all
      databases: all
      method: trust

  - name: change permissions 3
    postgresql_pg_hba:
      dest: /etc/postgresql/12/main/pg_hba.conf
      contype: host
      users: all
      source: 127.0.0.1/32
      databases: all
      method: trust

  - name: change permissions 4
    postgresql_pg_hba:
      dest: /etc/postgresql/12/main/pg_hba.conf
      contype: host
      users: all
      source: ::1/128
      databases: all
      method: trust

